[
  {
    id: 465,
    question: "Which of the following encoding an XML parser assumes ?",
    description: null,
    answers: {
      answer_a: "UTF-16",
      answer_b: "UTF-32",
      answer_c: "UTF-8",
      answer_d: "UTF-64",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "true",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "true",
      answer_c_correct: "true",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Medium",
  },
  {
    id: 472,
    question: "Who is known as the father of world wide web (WWW)?",
    description: null,
    answers: {
      answer_a: "Robert Cailliau",
      answer_b: "Charles Darwin",
      answer_c: "Tim Thompson",
      answer_d: "Tim Berners-Lee",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "true",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Medium",
  },
  {
    id: 458,
    question: "Which \u043ef the following class centers tabs/pills?",
    description: null,
    answers: {
      answer_a: ".nav-justified",
      answer_b: ".nav.navbar-nav",
      answer_c: ".nav Nav-pills",
      answer_d: ".nav-stacked",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "true",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Medium",
  },
  {
    id: 538,
    question: "Choose the correct HTML tag for the smallest size heading?",
    description: null,
    answers: {
      answer_a: "<heading>",
      answer_b: "<head>",
      answer_c: "<h1>",
      answer_d: "<h6>",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "true",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Easy",
  },
  {
    id: 512,
    question: "Text within <EM> \u2026 </EM> tag is displayed as ________",
    description: null,
    answers: {
      answer_a: "bold",
      answer_b: "indented",
      answer_c: "list",
      answer_d: "italic",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "true",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Easy",
  },
  {
    id: 502,
    question: "Which tag inserts a line horizontally on your web page?",
    description: null,
    answers: {
      answer_a: "<hr>",
      answer_b: '<line direction="horizontal">',
      answer_c: "<tr>",
      answer_d: "<line>",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "true",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Easy",
  },
  {
    id: 488,
    question: "HTML Uses",
    description: null,
    answers: {
      answer_a: "Fixed Tags Defined By The Language",
      answer_b: "Pre-specified Tags",
      answer_c: "Tags Only For Linking",
      answer_d: "User Defined Tags",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "true",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Easy",
  },
  {
    id: 543,
    question: "What is cite tag in HTML5?",
    description: null,
    answers: {
      answer_a: '<cite title"value">Some Text Here</cite>',
      answer_b: '<cite title:"value">Some Text Here</cite>',
      answer_c: '<cite title="value">Some Text Here</cite>',
      answer_d: null,
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "true",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Easy",
  },
  {
    id: 469,
    question:
      "The __________ Element represents a span of text that is isolated from it's surroundings for the purposes of bidirectional text formatting",
    description: null,
    answers: {
      answer_a: "B",
      answer_b: "Base",
      answer_c: "Bdo",
      answer_d: "Bdi",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "true",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Medium",
  },
  {
    id: 532,
    question: "There are ____ different heading tags in HTML",
    description: null,
    answers: {
      answer_a: "4",
      answer_b: "7",
      answer_c: "6",
      answer_d: "5",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "true",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Easy",
  },
  {
    id: 459,
    question:
      "Which of the following will create the so called Hamburger Menu?",
    description: null,
    answers: {
      answer_a: "Icon-prev",
      answer_b: "Icon-next",
      answer_c: "Img-circle",
      answer_d: "Icon-bar",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "true",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Hard",
  },
  {
    id: 475,
    question: "How can you make A bulleted list with numbers?",
    description: null,
    answers: {
      answer_a: "<dl>",
      answer_b: "<ul>",
      answer_c: "<ol>",
      answer_d: "<list>",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "true",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Easy",
  },
  {
    id: 446,
    question: "All HTML Tags must be enclosed In?",
    description: null,
    answers: {
      answer_a: "? And !",
      answer_b: "# And #",
      answer_c: "{ And }",
      answer_d: "< And >",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "true",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Medium",
  },
  {
    id: 466,
    question:
      "Which of the following will provide additional Information about something?",
    description: null,
    answers: {
      answer_a: "Jumbotron",
      answer_b: "Item",
      answer_c: "Label-danger",
      answer_d: "Label",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "true",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Medium",
  },
  {
    id: 451,
    question: "To start a list using circles, use",
    description: null,
    answers: {
      answer_a: '<ul Type="circle">',
      answer_b: '<ul ="round">',
      answer_c: '<ul "round">',
      answer_d: '<ul Type="round">',
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "true",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Medium",
  },
  {
    id: 503,
    question: "Which tag allows you to add a row in a table?",
    description: null,
    answers: {
      answer_a: "<td> and </td>",
      answer_b: "<tr> and </tr>",
      answer_c: "<th> and </th>",
      answer_d: "<cr> and </cr>",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "true",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Easy",
  },
  {
    id: 506,
    question: "Which of the following are commonly found in web pages?",
    description: null,
    answers: {
      answer_a: "internet",
      answer_b: "hyperlinks",
      answer_c: "intranet",
      answer_d: "all of the above",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "true",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Easy",
  },
  {
    id: 480,
    question:
      "Which of the following attribute triggers event when an element gets user Input?",
    description: null,
    answers: {
      answer_a: "Ondata",
      answer_b: "Onloadeddata",
      answer_c: "Oninput",
      answer_d: "Onhaschange",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "true",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Medium",
  },
  {
    id: 463,
    question:
      "Which Tag is used if you want to indicate the importance of the phrase?",
    description: null,
    answers: {
      answer_a: "<h1>",
      answer_b: "<h2>",
      answer_c: "<strong>",
      answer_d: "<em>",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "true",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Medium",
  },
  {
    id: 462,
    question: "Which of the following adds a checkmark Icon inside an Input?",
    description: null,
    answers: {
      answer_a: "Help-block",
      answer_b: "Has-warning",
      answer_c: "Has-feedback",
      answer_d: "Has-success",
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: "false",
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "true",
      answer_c_correct: "false",
      answer_d_correct: "false",
      answer_e_correct: "false",
      answer_f_correct: "false",
    },
    correct_answer: "answer_a",
    explanation: null,
    tip: null,
    tags: [{ name: "HTML" }],
    category: "Code",
    difficulty: "Medium",
  },
];
